# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  Glad_config = debug
  SeePP_config = debug

else ifeq ($(config),release)
  Glad_config = release
  SeePP_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := Glad SeePP

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

Glad:
ifneq (,$(Glad_config))
	@echo "==== Building Glad ($(Glad_config)) ===="
	@${MAKE} --no-print-directory -C glad -f Makefile config=$(Glad_config)
endif

SeePP: Glad
ifneq (,$(SeePP_config))
	@echo "==== Building SeePP ($(SeePP_config)) ===="
	@${MAKE} --no-print-directory -C seepp/seepp -f Makefile config=$(SeePP_config)
endif

clean:
	@${MAKE} --no-print-directory -C glad -f Makefile clean
	@${MAKE} --no-print-directory -C seepp/seepp -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Glad"
	@echo "   SeePP"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"